.TH "gnuplotio::ModeSize" 3 "Mon Nov 25 2019" "Version 7.0" "Robot Controller Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::ModeSize \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBis_text\fP = 0"
.br
.ti -1c
.RI "static const bool \fBis_binfmt\fP = 0"
.br
.ti -1c
.RI "static const bool \fBis_size\fP = 1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Robot Controller Module from the source code\&.
