.TH "gnuplotio::TextSender< double >" 3 "Mon Nov 25 2019" "Version 7.0" "Robot Controller Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::TextSender< double > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgnuplotio::FloatTextSender< double >\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Robot Controller Module from the source code\&.
