.TH "gnuplotio::TextSender< char >" 3 "Mon Nov 25 2019" "Version 7.0" "Robot Controller Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::TextSender< char > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgnuplotio::CastIntTextSender< char >\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Robot Controller Module from the source code\&.
