.TH "gnuplotio::BinarySender< T, typename boost::enable_if< boost::mpl::and_< is_boost_tuple< T >, is_boost_tuple_nulltype< typename T::tail_type > > >::type >" 3 "Mon Nov 25 2019" "Version 7.0" "Robot Controller Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::BinarySender< T, typename boost::enable_if< boost::mpl::and_< is_boost_tuple< T >, is_boost_tuple_nulltype< typename T::tail_type > > >::type > \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsend\fP (std::ostream &stream, const T &v)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Robot Controller Module from the source code\&.
