.TH "gnuplotio::FileHandleWrapper" 3 "Mon Nov 25 2019" "Version 7.0" "Robot Controller Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::FileHandleWrapper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBgnuplotio::Gnuplot\fP\fC [private]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileHandleWrapper\fP (std::FILE *_fh, bool _should_use_pclose)"
.br
.ti -1c
.RI "void \fBfh_close\fP ()"
.br
.ti -1c
.RI "int \fBfh_fileno\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::FILE * \fBwrapped_fh\fP"
.br
.ti -1c
.RI "bool \fBshould_use_pclose\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Robot Controller Module from the source code\&.
