.TH "gnuplotio::BinarySender< boost::uint8_t >" 3 "Mon Nov 25 2019" "Version 7.0" "Robot Controller Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::BinarySender< boost::uint8_t > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgnuplotio::FlatBinarySender< boost::uint8_t >\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Robot Controller Module from the source code\&.
