.TH "md__home_rajshinde__g_m_o_c_k__robot__controller__module__r_e_a_d_m_e" 3 "Mon Nov 25 2019" "Version 7.0" "Robot Controller Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_rajshinde__g_m_o_c_k__robot__controller__module__r_e_a_d_m_e \- Robot Controller Module 
\fC\fP \fC\fP \fC\fP 
.SS "\fC\fP "
.PP
.SS "Authors"
.PP
.IP "\(bu" 2
\fBRaj Prakash Shinde\fP - \fISprint 1- Driver & Sprint 2- Navigator\fP - \fCGitHub\fP 
.br
I am a Masters in Robotics Engineering student at the University of Maryland, College Park\&. My primary area of interest are Legged Robotics and Automation\&.
.IP "\(bu" 2
\fBPrasheel Renkuntla\fP - \fISprint 1- Navigator & Sprint 2- Driver\fP - \fCGitHub\fP 
.br
I am a Master's in Robotics Engineering student at the University of Maryland, College Park\&. My primary area of interest is in Vision integrated Robot Systems\&.
.PP
.PP
.SS "Overview"
.PP
This is a controller module for a robot that uses an Ackermann Steering Model, This controller is to be implemented in a four wheeled Robot made by ACME Robotics\&.
.PP
.SS "Description"
.PP
A controller is build for a 4 wheeled robot with an Ackermann steering to navigate through its environment\&. The controller consist of a PID algorithm which ensures that the velocity converges to the set point, and a Steer Algorithm that helps the robot turn\&. 
.br
The PID Algorithm is a control loop mechanism that calculates the error and applies correction through proportional, integral and derivative gains\&. The Steer Algorithm is developed to turn the robot, which is done by calculating the length of an arc inscribed between the current robot heading and target heading, the length when divided by the robot velocity gives the time for which the wheels need to be kept at angles given by Ackermann steering Model\&. 
.br
The input to the controller will be provided by the perception model developed by the ACME Robotics\&. 
.br
The Demonstration of the controller will be given by plotting a graph that shows convergence of velocity & Heading angle to the targets with respect to time\&.
.PP
.SS "Features"
.PP
.IP "\(bu" 2
Velocity control during turning\&.
.IP "\(bu" 2
Protection against Skidding, by limiting velocity during turning\&.
.IP "\(bu" 2
Protection agains over volting the Motors\&.
.PP
.PP
.SS "Application"
.PP
.IP "\(bu" 2
Mobile Wheeled Robots
.PP
.PP
.SS "Sprint Planning and Discussion"
.PP
Sprint- https://docs.google.com/document/d/1w6U49tyKj9MFhaVziZ5MEGcaylmxSBOyGzClIz9lFA8/edit?usp=sharing
.PP
.SS "Agile Iterative Process Log"
.PP
Log- https://docs.google.com/spreadsheets/d/1LFQMKbuGeusgmI7IMbjiw-RJrt9jNgej0F8SvvfyJjY/edit?usp=sharing
.PP
.SS "Dependencies"
.PP
.IP "1." 4
C++ 11/14/17
.IP "2." 4
gnuplot- http://stahlke.org/dan/gnuplot-iostream/ 
.br
Install gnuplot 
.PP
.nf
1 sudo apt-get install gnuplot

.fi
.PP

.IP "3." 4
boost 
.br
Install boost 
.PP
.nf
1 sudo apt-get install libboost-all-dev

.fi
.PP

.PP
.PP
## Build 
.PP
.nf
1 git clone --recursive https://github\&.com/RajPShinde/Robot_Controller_Module\&.git
2 cd <path to repository>
3 mkdir build
4 cd build
5 cmake \&.\&.
6 make

.fi
.PP
 
.SS "Run"
.PP
#### Run Program 
.PP
.nf
1 \&./app/shell-app

.fi
.PP
 #### Run Test 
.PP
.nf
1 \&./test/cpp-test

.fi
.PP
 
.SS "Gererate Doxygen docs"
.PP
In a new terminal 
.PP
.nf
1 sudo apt-get install doxygen
2 sudo apt install doxygen-gui
3 doxywizard

.fi
.PP
 
.SS "Demo"
.PP
Run the program\&. Once the velocity and heading converge to the target then graphs will be displayed as below\&. Also, converged values will be shown in the terminal\&.
.PP
.SS "Heading Convergence"
.PP
 
.PP
.SS "Velocity Convergence"
.PP
 
.PP
.SS "Terminal Output"
.PP
 
.PP
.SS "Bugs"
.PP
None
.PP
.SS "References"
.PP
.IP "\(bu" 2
Ackermann Steering- https://www.sciencedirect.com/topics/engineering/ackermann
.IP "\(bu" 2
PID Controller- https://en.wikipedia.org/wiki/PID_controller
.IP "\(bu" 2
gnuplot- http://stahlke.org/dan/gnuplot-iostream/ 
.PP

