.TH "MockNavigation" 3 "Mon Nov 25 2019" "Version 7.0" "Robot Controller Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MockNavigation \- Mock \fBNavigation\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MockNavigation\&.hpp>\fP
.PP
Inherits \fBNavigation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMockNavigation\fP ()"
.br
.RI "\fIDefault constructor\&. \fP"
.ti -1c
.RI "\fBMOCK_METHOD0\fP (\fBgetKp_\fP, double())"
.br
.RI "\fIMock getKp_\&. \fP"
.ti -1c
.RI "\fBMOCK_METHOD4\fP (\fBcalculate\fP, double(double targetHeading, double currentVelocity, double setPoint, int flag))"
.br
.RI "\fIMock calculate method\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Mock \fBNavigation\fP class\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Robot Controller Module from the source code\&.
