.TH "include/Navigation.hpp" 3 "Mon Oct 14 2019" "Version 1.0" "Robot Controller Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Navigation.hpp \- Mid Term Project\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'SteerAlgorithm\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNavigation\fP"
.br
.RI "\fIClass \fBNavigation\fP Contains the methods of Pid Algorithm\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Mid Term Project\&. 


.PP
\fBCopyright:\fP
.RS 4
MIT License, Copyright © 2019 Raj Shinde
.RE
.PP
\fBAuthor:\fP
.RS 4
Sprint-1 Raj Shinde- driver and Prasheel Renkuntla- navigator 
.PP
Sprint-2 Prasheel Renkuntla- driver and Raj Shinde- navigator 
.RE
.PP
\fBDate:\fP
.RS 4
10/10/2019 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Robot Controller Module from the source code\&.
