.TH "Navigation" 3 "Mon Nov 25 2019" "Version 7.0" "Robot Controller Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Navigation \- Class \fBNavigation\fP Contains the methods of steer Algorithm\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Navigation\&.hpp>\fP
.PP
Inherits \fBSteerAlgorithm\fP\&.
.PP
Inherited by \fBMockNavigation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNavigation\fP ()"
.br
.RI "\fIConstructor of class \fBNavigation\fP\&. \fP"
.ti -1c
.RI "\fB~Navigation\fP ()"
.br
.RI "\fIDestructor of class \fBNavigation\fP\&. \fP"
.ti -1c
.RI "double \fBcalculate\fP (double targetHeading, double currentVelocity, double setPoint, int flag)"
.br
.RI "\fIFunction to calculate new velocity in m/s with a PID Algorithm using kp, ki & kd\&. \fP"
.ti -1c
.RI "bool \fBsetupGraph\fP ()"
.br
.RI "\fIFunction to set graph parameters\&. \fP"
.ti -1c
.RI "bool \fBdisplay\fP (int loc, double currentVelocity, double newVelocity, double heading, double targetHeading)"
.br
.RI "\fIFunction to display on Terminal\&. \fP"
.ti -1c
.RI "bool \fBdrawGraph\fP (std::vector< std::pair< double, double >> points, std::vector< std::pair< double, double >> pointsVelocity, double newVelocity, double tempHeading)"
.br
.RI "\fIFunction to draw graphs in gnuplot\&. \fP"
.ti -1c
.RI "double \fBgetKp_\fP ()"
.br
.RI "\fIFunction to get kp_\&. \fP"
.ti -1c
.RI "double \fBgetKi_\fP ()"
.br
.RI "\fIFunction to get ki_\&. \fP"
.ti -1c
.RI "double \fBgetKd_\fP ()"
.br
.RI "\fIFunction to get kd_\&. \fP"
.ti -1c
.RI "bool \fBsetKp_\fP (double kp)"
.br
.RI "\fIFunction to set kp_\&. \fP"
.ti -1c
.RI "bool \fBsetKi_\fP (double ki)"
.br
.RI "\fIFunction to set ki_\&. \fP"
.ti -1c
.RI "bool \fBsetKd_\fP (double kd)"
.br
.RI "\fIFunction to set kd_\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBmotorDirection\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBNavigation\fP Contains the methods of steer Algorithm\&. 
.SH "Member Function Documentation"
.PP 
.SS "double Navigation::calculate (double targetHeading, double currentVelocity, double setPoint, int flag)"

.PP
Function to calculate new velocity in m/s with a PID Algorithm using kp, ki & kd\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdouble\fP targetHeading, Target heading of the robot 
.br
\fIdouble\fP currentVelocity, current velocity of robot 
.br
\fIdouble\fP setPoint, Target Velocity 
.br
\fIint\fP flag, to enable while 
.RE
.PP
\fBReturns:\fP
.RS 4
double newVelocity 
.RE
.PP

.SS "bool Navigation::display (int loc, double currentVelocity, double newVelocity, double heading, double targetHeading)"

.PP
Function to display on Terminal\&. 
.PP
\fBParameters:\fP
.RS 4
\fIint\fP loc 
.br
\fIdouble\fP currentVelocity 
.br
\fIdouble\fP newVelocity 
.br
\fIdouble\fP heading 
.br
\fIdouble\fP targetHeading 
.RE
.PP
\fBReturns:\fP
.RS 4
none 
.RE
.PP

.SS "bool Navigation::drawGraph (std::vector< std::pair< double, double >> points, std::vector< std::pair< double, double >> pointsVelocity, double newVelocity, double tempHeading)"

.PP
Function to draw graphs in gnuplot\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvector<pair<double,double>>\fP points 
.br
\fIvector<pair<double,double>>\fP pointsVelocity 
.br
\fIdouble\fP newVelocity 
.br
\fIdouble\fP tempHeading 
.RE
.PP
\fBReturns:\fP
.RS 4
none 
.RE
.PP

.SS "double Navigation::getKd_ ()"

.PP
Function to get kd_\&. 
.PP
\fBParameters:\fP
.RS 4
\fInone\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
double 
.RE
.PP

.SS "double Navigation::getKi_ ()"

.PP
Function to get ki_\&. 
.PP
\fBParameters:\fP
.RS 4
\fInone\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
double 
.RE
.PP

.SS "double Navigation::getKp_ ()"

.PP
Function to get kp_\&. 
.PP
\fBParameters:\fP
.RS 4
\fInone\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
double 
.RE
.PP

.SS "bool Navigation::setKd_ (double kd)"

.PP
Function to set kd_\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdouble\fP kd 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean true 
.RE
.PP

.SS "bool Navigation::setKi_ (double ki)"

.PP
Function to set ki_\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdouble\fP ki 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean true 
.RE
.PP

.SS "bool Navigation::setKp_ (double kp)"

.PP
Function to set kp_\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdouble\fP kp 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean true 
.RE
.PP

.SS "bool Navigation::setupGraph ()"

.PP
Function to set graph parameters\&. 
.PP
\fBParameters:\fP
.RS 4
\fInone\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
none 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Robot Controller Module from the source code\&.
