.TH "app/SteerAlgorithm.cpp" 3 "Mon Oct 21 2019" "Version 5" "Ackermann Steering Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/SteerAlgorithm.cpp \- Mid Term Project\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include 'SteerAlgorithm\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
Mid Term Project\&. 


.PP
\fBCopyright:\fP
.RS 4
MIT License, Copyright © 2019 Raj Shinde
.RE
.PP
\fBAuthor:\fP
.RS 4
Sprint-1 Raj Shinde- driver and Prasheel Renkuntla- navigator 
.PP
Sprint-2 Prasheel Renkuntla- driver and Raj Shinde- navigator 
.RE
.PP
\fBDate:\fP
.RS 4
10/10/2019 
.RE
.PP
\fBVersion:\fP
.RS 4
6\&.0 
.RE
.PP
.SH "Ackermann on PID control"
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Ackermann Steering Control from the source code\&.
