.TH "test/testNavigation.cpp" 3 "Mon Oct 21 2019" "Version 5" "Ackermann Steering Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/testNavigation.cpp \- Mid Term Project\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <memory>\fP
.br
\fC#include 'Navigation\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (\fBNavigation\fP, testSetPid)"
.br
.RI "\fITest to check the set functions for kp_,ki_ and kd_\&. \fP"
.ti -1c
.RI "\fBTEST\fP (\fBNavigation\fP, testGetPid)"
.br
.RI "\fITest to check that values of kp_,ki_ and kd_ are below 1 or not\&. \fP"
.ti -1c
.RI "\fBTEST\fP (\fBNavigation\fP, testConvergence)"
.br
.RI "\fITest to check the output of calculate function converges with the setPoint and Heading\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Mid Term Project\&. 


.PP
\fBCopyright:\fP
.RS 4
MIT License, Copyright © 2019 Raj Shinde
.RE
.PP
\fBAuthor:\fP
.RS 4
Sprint-1 Raj Shinde- driver and Prasheel Renkuntla- navigator 
.PP
Sprint-2 Prasheel Renkuntla- driver and Raj Shinde- navigator 
.RE
.PP
\fBDate:\fP
.RS 4
10/10/2019 
.RE
.PP
\fBVersion:\fP
.RS 4
6\&.0 
.RE
.PP
.SH "all files in module"
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Ackermann Steering Control from the source code\&.
